### ISSUE TITLE
add link to results page/leo forums

### ISSUE THREAD

**Issue by mooseyboots** [mtenders/leo#1]
thanks for this package, it's great to be able to access leo.de results in emacs, and fast.

i just thought to ask if if would be feasible to add an optional link (browse-url external) to the results page of a search.

the main use case being that if there are no results in the dictionary, leo.el returns nothing. but on leo.de there are often forum discussions about terms not found in the official dictionary.

i guess that an ext link option would be much easier than adding forum posts to the leo.el results.

**Comment by mtenders** [comment]
Hi,

thanks for the suggestion! I'll try to add it this weekend.

**Comment by mtenders** [comment]
Now it should also display the forum post as clickable buttons (2ab30fe). @mooseyboots , could you try if it works for you?
