### ISSUE TITLE
fork with various new features

### ISSUE THREAD

**Issue by mooseyboots** [mtenders/leo#3]
i have been adding quite a few things to my fork of your repo.

https://github.com/mooseyboots/emacs-leo/tree/develop

i wonder if you cd take a look at it?

i added part of speech headings, results are links (click or tab/ret) to search for themselves, suggested clickable search terms if no results, binding to jump to results in browser, propertized search term in results, links to conjugation/inflexion tables, prefix arg to chose language, and other things.

it still needs a little work to parse all the extra bits of information correctly in all cases, and the quality of the code could be improved, but most things are working well for me and another tester.

i'd be interested in hearing what you think, and if you want to incorporate my work.

**Comment by mtenders** [comment]
Wow, thanks a lot for all the work! I'll have a look on the weekend.

**Comment by mtenders** [comment]
I just merged your changes into this repository.

**Comment by martianhi** [comment]
@mtenders thx for taking it on! the code is a bit (very) messy as i was learning a lot of new things while hacking away, but for what it is it seems to work ok ok.

**Comment by martianhi** [comment]
@mtenders i have a bunch of updates since last merge. i think its mostly less hacky/buggy now. maybe take a look when you have a moment: https://codeberg.org/martianh/emacs-leo
