### ISSUE TITLE
leo-translate-at-point runs with error in shr-map (emacs 26.1)

### ISSUE THREAD

**Issue by thjwong** [mtenders/leo#6]
I am running Emacs 26.1
`GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2021-01-31, modified by Debian
`

I downloaded leo.el and leo-inspect.el to my elisp folder and loaded both of them before calling 
`(require 'leo)`

Upon calling `leo-translate-at-point`, I get the following error:

```
Contacting host: dict.leo.org:443
let*: Symbol’s value as variable is void: shr-map
```

`leo--search-term-with-dictcc` and `dictcc-at-point` both run without any problem.

**Comment by martianhi** [comment]
@thjwong thanks for yr feedback.

i will push a change to deal with this.

in the meantime, do you still have this issue if you run `eval-expression RET (require 'shr)`?

i tried that in a sandboxed build and the error disappeared for me.

**Comment by martianhi** [comment]
feel free to re-open if you still have trouble with this.
